#!/usr/bin/env python3
"""Extract vineyard_sources from wines.yaml into wine_vineyard_sources.yaml (one-off transform)."""

from pathlib import Path

import yaml

SEED = Path(__file__).resolve().parent.parent / "data" / "seed"
WINES_PATH = SEED / "wines.yaml"
OUT_PATH = SEED / "wine_vineyard_sources.yaml"
SECTION_COMMENT = (
    "# Major wines — flagship and notable bottlings "
    "(curated; vineyard_sources moved to wine_vineyard_sources.yaml).\n"
)


def main() -> None:
    text = WINES_PATH.read_text(encoding="utf-8")
    lines = text.splitlines()
    header_end = 0
    for i, line in enumerate(lines):
        if line.startswith("- ") and "label_name" in line:
            header_end = i
            break
    header = "\n".join(lines[:header_end]) + "\n\n"

    wines = yaml.safe_load(text)
    if not isinstance(wines, list):
        raise SystemExit("wines.yaml must be a YAML list")

    flat: list[dict] = []
    for w in wines:
        if not isinstance(w, dict):
            continue
        vs = w.pop("vineyard_sources", None)
        if vs:
            for vsrc in vs:
                if not isinstance(vsrc, dict):
                    continue
                row: dict = {
                    "winery": w["winery"],
                    "label_name": w["label_name"],
                    "vintage_year": w["vintage_year"],
                    "vineyard": vsrc["vineyard"],
                }
                if vsrc.get("block_name") is not None:
                    row["block_name"] = vsrc["block_name"]
                if vsrc.get("pct_blend") is not None:
                    row["pct_blend"] = vsrc["pct_blend"]
                flat.append(row)

    OUT_PATH.write_text(
        "# Wine vineyard sources (fruit sourcing). Generated by "
        "scripts/extract_wine_vineyard_sources.py from nested wines.yaml data.\n\n"
        + yaml.dump(
            flat,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        ),
        encoding="utf-8",
    )

    dumped = yaml.dump(
        wines,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )
    anchor = '- label_name: "Hahn Santa Lucia Highlands Pinot Noir"\n'
    if anchor in dumped:
        dumped = dumped.replace(anchor, SECTION_COMMENT + anchor, 1)

    WINES_PATH.write_text(header + dumped, encoding="utf-8")
    print(f"Wrote {len(flat)} rows to {OUT_PATH}")
    print(f"Updated {WINES_PATH} (removed vineyard_sources keys)")


if __name__ == "__main__":
    main()
