"""initial_schema

Revision ID: 817101459347
Revises: 
Create Date: 2026-04-05 21:28:45.316104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817101459347'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ava',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('parent_ava_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('ttb_approval_date', sa.Date(), nullable=True),
    sa.Column('total_acres', sa.Integer(), nullable=True),
    sa.Column('planted_acres', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_ava_id'], ['ava.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grape_variety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_synonyms', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('origin_region', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vineyard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ava_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_ft_low', sa.Integer(), nullable=True),
    sa.Column('elevation_ft_high', sa.Integer(), nullable=True),
    sa.Column('total_acres', sa.Integer(), nullable=True),
    sa.Column('soil_type', sa.Text(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ava_id'], ['ava.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_state', sa.Text(), nullable=True),
    sa.Column('ava_id', sa.Integer(), nullable=True),
    sa.Column('is_negociant', sa.Boolean(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ava_id'], ['ava.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vineyard_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vineyard_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ownership_role', sa.Text(), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['vineyard_id'], ['vineyard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winery_id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.Text(), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('grape_variety_id', sa.Integer(), nullable=True),
    sa.Column('ava_id', sa.Integer(), nullable=True),
    sa.Column('alcohol_pct', sa.Float(), nullable=True),
    sa.Column('production_cases', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('tasting_notes', sa.Text(), nullable=True),
    sa.Column('winery_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ava_id'], ['ava.id'], ),
    sa.ForeignKeyConstraint(['grape_variety_id'], ['grape_variety.id'], ),
    sa.ForeignKeyConstraint(['winery_id'], ['winery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winery_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winery_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['winery_id'], ['winery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wine_grape_variety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('grape_variety_id', sa.Integer(), nullable=False),
    sa.Column('pct_blend', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['grape_variety_id'], ['grape_variety.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wine_id', 'grape_variety_id')
    )
    op.create_table('wine_vineyard_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('vineyard_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.Text(), nullable=True),
    sa.Column('pct_blend', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vineyard_id'], ['vineyard.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wine_id', 'vineyard_id', 'block_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine_vineyard_source')
    op.drop_table('wine_grape_variety')
    op.drop_table('winery_staff')
    op.drop_table('wine')
    op.drop_table('vineyard_owner')
    op.drop_table('winery')
    op.drop_table('vineyard')
    op.drop_table('person')
    op.drop_table('grape_variety')
    op.drop_table('ava')
    # ### end Alembic commands ###
